apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: trackunit
spec:
# Making sure we have 2 instances running.
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        name: httpbin
        ports:
        - containerPort: 80
# Adding Liveness Probe
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
# Adding security best practices
# Setting limits and request for the application
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 200m
            memory: 1G
# Setting up HPA to manage the load (Not sure if this is a security best practice)
# Metrics are not available for the HPA in this example
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: httpbin-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: httpbin
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50